name: init-check
on:
  push:
    branches:
      - master
jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          args: "-no-fail -fmt sarif -out results.sarif ../../../../webapp"
