name: dynamic_zap_scan
on:
  push:
    branches:
      - master
jobs:
  scan-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go build & go run webapp/.

      # - name: Run ZAP
      # - uses: zaproxy/action-baseline@v0.6.1
      #   with:
      #     docker_name: 'owasp/zap2docker-stable'
      #     target: 'localhost:8080'
      #     cmd_options: '-a'