name: dynamic_zap_scan
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - name: upload app
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-68-33-121.eu-central-1.compute.amazonaws.com
          username: ec2-user
          password: securitytest
          source: "webapp/*"
          target: "webapp"
      - name: Launch remote app
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-68-33-121.eu-central-1.compute.amazonaws.com
          username: ec2-user
          password: securitytest
          script: pkill -f tmux && tmux new -d 'cd webapp/webapp/ && go run .'
      - uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: "owasp/zap2docker-stable"
          target: "localhost:8080"
          cmd_options: "-a"
