name: dynamic_zap_scan
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - name: upload app
        run: apt install -y sshpass & sshpass ${{secrets.SSH_PASS}} scp -r webapp ec2-user@ec2-3-68-33-121.eu-central-1.compute.amazonaws.com:/home/ec2-user
      - uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: "owasp/zap2docker-stable"
          target: "localhost:8080"
          cmd_options: "-a"
